version: '2'
services:

  mysql:
    image: mysql:5.7
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=vKxkoF0E82vD
      - MYSQL_ROOT_PASSWORD=zLwY30UVdHV8
    # development only
    ports:
      - "13306:3306"

  zabbix_server:
    image: zabbix/zabbix-server-mysql:alpine-4.0.1
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=vKxkoF0E82vD
      - MYSQL_ROOT_PASSWORD=zLwY30UVdHV8
      # 0 - basic information about starting and stopping of Zabbix processes;
      # 1 - critical information
      # 2 - error information
      # 3 - warnings
      # 4 - for debugging (produces lots of information)
      # 5 - extended debugging (produces even more information)
      - ZBX_DEBUGLEVEL=3
    ports:
      - "10051:10051"
    links:
      - mysql

  zabbix_web:
    image: zabbix/zabbix-web-apache-mysql:alpine-4.0.1
    environment:
      - ZBX_SERVER_HOST=zabbix_server
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=vKxkoF0E82vD
      - MYSQL_ROOT_PASSWORD=zLwY30UVdHV8
      - PHP_TZ=Asia/Tokyo
    ports:
      - 80:80
    links:
      - zabbix_server
      - mysql

  zabbix_agent:
    image: zabbix/zabbix-agent:alpine-4.0.1
    privileged: true
    environment:
      - ZBX_SERVER_HOST=zabbix_server
    expose:
      - "10050"
    links:
      - zabbix_server
