- name: install node-red
  npm: name=node-red state=latest global=yes
  tags: node-red

- name: create systemd service
  template: src=node-red.service dest=/etc/systemd/system/node-red.service owner=root group=root mode=0644
  tags: node-red
  notify: reload services

- name: enable and start service
  service: name=node-red state=started enabled=yes
  tags: node-red

- name: create desktop shortcut
  template: src=Node-RED.desktop dest=/home/pi/Desktop/Node-RED.desktop owner=pi group=pi mode=0644
  tags: node-red
